// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The window says its first frame is on screen, which is where cold start ends.
	 * 
	 *  It is silent unless `CHARTER_BENCH_LOG` is set — only `tools/bench.mjs` sets it — so in
	 *  an ordinary run this is one IPC call at startup that does nothing.
	 */
	firstFrame: () => __TAURI_INVOKE<void>("first_frame"),
	/**  The plane the app was started in, or why there is none. */
	planeRoot: () => typedError<string, string>(__TAURI_INVOKE("plane_root")),
	/**
	 *  Starts a session, and remembers it as a chat so a quit can write it down. No program is
	 *  the operator's shell.
	 */
	openSession: (program: string | null, args: string[], cwd: string | null, name: string, columns: number, rows: number) => typedError<number, string>(__TAURI_INVOKE("open_session", { program, args, cwd, name, columns, rows })),
	/**  Ends a session and everything it started. It is no longer a chat a quit would record. */
	closeSession: (session: number) => typedError<null, string>(__TAURI_INVOKE("close_session", { session })),
	/**  Sends what a pane typed to the session's program. */
	sendInput: (session: number, text: string) => typedError<null, string>(__TAURI_INVOKE("send_input", { session, text })),
	/**  Tells a session how big the pane showing it now is. */
	resizeSession: (session: number, columns: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_session", { session, columns, rows })),
	/**
	 *  Opens a view of a session for a pane that is now on screen: the channel is sent the screen
	 *  as it already is, and then the session's output. Answers with the id that closes the view.
	 */
	watchSession: (session: number, output: Channel<string>) => typedError<Watching, string>(__TAURI_INVOKE("watch_session", { session, output })),
	/**  Closes a view, for a pane that has gone off screen. The session keeps running. */
	unwatchSession: (session: number, view: number) => typedError<null, string>(__TAURI_INVOKE("unwatch_session", { session, view })),
	/**  The sessions that are running, in the order they were opened. */
	runningSessions: () => __TAURI_INVOKE<number[]>("running_sessions"),
	/**
	 *  What every chat is doing, and which of them are asking for you.
	 * 
	 *  The window asks once, when it opens; after that it is told (`chat-moved`). A chat the app
	 *  has never heard from is `unknown`, which is what the spec says a harness with no state
	 *  hook shows.
	 */
	chatStates: () => __TAURI_INVOKE<Moved[]>("chat_states"),
	/**
	 *  Why this chat can never report its state, where it cannot.
	 * 
	 *  Codex is the case: its hooks live only in a machine-wide file, and it fires no
	 *  `Notification` at all. A chat showing `unknown` with no reason looks like charter is
	 *  broken rather than like the harness is different.
	 */
	whyUnknown: (session: number) => __TAURI_INVOKE<string | null>("why_unknown", { session }),
	/**
	 *  The chats the app already has open — at a launch, the ones put back from the record.
	 * 
	 *  The window asks this instead of opening its own: putting the record back happens before
	 *  there is a window, so that a relaunch does not depend on a webview having run.
	 */
	openedChats: () => __TAURI_INVOKE<OpenChat[]>("opened_chats"),
	/**
	 *  The chats this launch could not start, by name and reason. They are still recorded, and
	 *  will be tried again at the next launch.
	 */
	chatsThatWouldNotStart: () => __TAURI_INVOKE<([string, string])[]>("chats_that_would_not_start"),
	/**  Says which chat is in front, so the record brings that one back in front. */
	chatInFront: (session: number | null) => __TAURI_INVOKE<void>("chat_in_front", { session }),
	/**
	 *  Asks the app to quit, the way the menu's Quit and the tray's do.
	 * 
	 *  It is the same function they call, so what this goes through is the real path: the ask
	 *  is counted, the window is shown, and the window is sent `quit-asked`. The command
	 *  palette's own quit action is this too.
	 */
	askToQuit: () => __TAURI_INVOKE<void>("ask_to_quit"),
	/**  The window's answer to being asked to quit: go. */
	quit: () => __TAURI_INVOKE<void>("quit"),
	/**  The window's answer to being asked to quit: not now. The next ask warns again. */
	quitCancelled: () => __TAURI_INVOKE<void>("quit_cancelled"),
	/**  Hides the window, which is what its close button does. Every session keeps running. */
	hideWindow: () => __TAURI_INVOKE<void>("hide_window"),
	/**  Whether the window is on screen. The scenario tests ask; nothing in the UI does. */
	windowShowing: () => __TAURI_INVOKE<boolean>("window_showing"),
	/**
	 *  The sidebar, read from the plane on disk every time it is asked for.
	 * 
	 *  Read fresh rather than cached: the plane is a directory the operator also edits by hand
	 *  and another charter process writes, so a cache here would be a second answer to "what is
	 *  on disk" that nothing invalidates.
	 * 
	 *  The chats are the ones `Chats` already holds — one model of a chat, not a second derived
	 *  from the sessions. What files one under a workspace is the directory it works in, because
	 *  nothing on the plane records a chat: `.charter/frame/` belongs to the tmux frame and the
	 *  app stays out of it.
	 */
	planeSidebar: () => typedError<Sidebar, string>(__TAURI_INVOKE("plane_sidebar")),
	/**
	 *  The focused workspace's panels: its repos, its todos and the plane's personas.
	 * 
	 *  Its own command, separate from the repos below, because everything here is a directory
	 *  listing and a few small files. The panels paint the moment a workspace is focused, and
	 *  the part that has to run git arrives after — one command would make the todo list wait
	 *  for a status read on every clone.
	 */
	workspacePanels: (workspace: string) => typedError<Panels, string>(__TAURI_INVOKE("workspace_panels", { workspace })),
	/**
	 *  What git says about each of the focused workspace's clones, and what the forge cache
	 *  last recorded for the branch each is on.
	 * 
	 *  On a blocking thread and never the one that draws: a status read is bounded at five
	 *  seconds per clone, and a window that waited on it would miss the 100 ms a workspace
	 *  switch is allowed. **Nothing here crosses a network** — the forge state comes out of
	 *  `.charter/cache/glstate.json`, which charter-app reads and never writes.
	 */
	workspaceRepos: (workspace: string) => typedError<RepoStates, string>(__TAURI_INVOKE("workspace_repos", { workspace })),
	/**
	 *  What the picker draws: every profile this machine has, every one charter will not use,
	 *  and the plane's personas.
	 * 
	 *  Read fresh every time it is opened, like the sidebar: `charter.local.toml` is a file the
	 *  operator edits by hand and a chat can write, so a cache here would be a second answer to
	 *  "what is on disk" that nothing invalidates.
	 */
	startOptions: () => typedError<StartOptions, string>(__TAURI_INVOKE("start_options")),
	/**
	 *  Records that the operator approved running this profile's command — **the one they were
	 *  shown**.
	 * 
	 *  `shown` is the exact line the dialog drew. It is checked against the file again here,
	 *  and a mismatch refuses: between the picker reading the profile and the operator pressing
	 *  the button, `charter.local.toml` can change — it is gitignored, so an edit to it leaves
	 *  no diff for a reviewer to catch, and nothing stops a chat writing plane config. Without
	 *  this check the approval recorded whatever was on disk at CLICK time, so the operator
	 *  could approve, and charter could run, a command they never read. A review probe found
	 *  it, and it defeats the one prompt ADR 0022 exists to put in front of a launch.
	 * 
	 *  Its own command, and a separate click from the one that starts the chat: this IS the
	 *  approval, and a command that both asked and ran would be asking nothing.
	 */
	approveProfile: (name: string, shown: string) => typedError<null, string>(__TAURI_INVOKE("approve_profile", { name, shown })),
	/**
	 *  Starts a chat on a harness profile, with a persona.
	 * 
	 *  A command of its own rather than a flag on `open_session`, so neither can be mistaken
	 *  for the other by a caller passing null: this one goes through every gate a launch has,
	 *  and that one opens the operator's shell.
	 */
	startChat: (profile: string, persona: string | null, cwd: string | null, name: string, columns: number, rows: number) => typedError<Started, string>(__TAURI_INVOKE("start_chat", { profile, persona, cwd, name, columns, rows })),
	/**
	 *  The piece a chat's working directory sits in, or `None`.
	 * 
	 *  Called for every chat the sidebar draws. `worktree::locate` is path arithmetic and spawns
	 *  nothing; the one git call is the listing, made once per repo and only for chats that are
	 *  in a piece at all.
	 */
	worktreeOfChat: (cwd: string) => typedError<{
	workspace: string,
	repo: string,
	piece: string,
	branch: string | null,
	wired: boolean,
	stale: boolean,
} | null, string>(__TAURI_INVOKE("worktree_of_chat", { cwd })),
	/**  This workspace's pieces for one repo. */
	worktreeList: (plane: string, workspace: string, repo: string) => typedError<Piece[], string>(__TAURI_INVOKE("worktree_list", { plane, workspace, repo })),
	/**
	 *  Remove a piece. The refusal is the core's sentence, unchanged.
	 * 
	 *  `force` is the operator saying to discard work the guards found — it is never passed on
	 *  their behalf, and the window asks for it only after showing them what the refusal said.
	 */
	worktreeRemove: (plane: string, workspace: string, repo: string, piece: string, force: boolean) => typedError<null, string>(__TAURI_INVOKE("worktree_remove", { plane, workspace, repo, piece, force })),
	/**  Land a piece in its clone, fast-forward only. Never pushes. */
	worktreeMerge: (plane: string, workspace: string, repo: string, piece: string) => typedError<Merged, string>(__TAURI_INVOKE("worktree_merge", { plane, workspace, repo, piece })),
};

/* Types */
/**  Where a chat is working, when it is working in a piece. */
export type ChatWorktree = {
	workspace: string,
	repo: string,
	piece: string,
	branch: string | null,
	wired: boolean,
	stale: boolean,
};

/**  What a merge did, for the window to report. */
export type Merged = {
	branch: string,
	was: string,
	now: string,
};

/**  The event the window listens for. One chat, its state, whether it is asking for you. */
export type Moved = {
	session: number,
	state: string,
	needs_you: boolean,
	/**
	 *  Every chat asking for you, so the queue is never assembled from a series of events
	 *  the window might have missed one of.
	 */
	queue: number[],
};

/**  One chat the app has open, as the UI draws it and as the quit warning lists it. */
export type OpenChat = {
	session: number,
	name: string,
	cwd: string | null,
	/**  The harness it runs, by the word the plane calls it — or none for a shell. */
	harness: string | null,
	/**  Whether it is the chat to show: at a launch, the one that was in front at the quit. */
	in_front: boolean,
	/**  The conversation it was resumed by, where it was. The UI says which happened. */
	resumed: string | null,
	/**  Why it is a new chat rather than the one it was, where it is. */
	fresh: string | null,
	/**  The harness profile it started on, where it started on one. */
	profile: string | null,
	/**  The persona it adopted. */
	persona: string | null,
};

/**  One open todo. There is no state field: a closed todo is a deleted file (ADR 0004). */
export type PanelTodo = {
	/**  The file stem, which is what a todo is closed by. */
	slug: string,
	title: string,
	/**  The date the todo was written, as the file records it. */
	stamp: string,
};

/**  Everything the panels can draw without running git. */
export type Panels = {
	/**
	 *  The workspace this is about, so a late answer can be matched to the ask and an answer
	 *  for a workspace that is no longer focused can be thrown away.
	 */
	workspace: string,
	/**  The clones on disk, by name, in the order the directory lists them. */
	repos: string[],
	/**  Repos `workspace.json` names that are not cloned here. Membership, not presence. */
	absent: string[],
	/**
	 *  What charter would not look at, by name and reason. Shown, never dropped: a row that
	 *  is missing is otherwise merely missing.
	 */
	refused: ([string, string])[],
	todos: PanelTodo[],
	/**
	 *  Why the todos could not be read, where they could not. A store that is a link out of
	 *  the plane is refused, and "no todos" would be the wrong thing to draw for it.
	 */
	todos_refused: string | null,
	/**  The plane's personas, and the one a chat started here would adopt. */
	personas: string[],
	persona: string | null,
};

/**  One piece, as the window shows it. */
export type Piece = {
	piece: string,
	path: string,
	branch: string | null,
	/**
	 *  Whether charter's harness layer is in this tree.
	 * 
	 *  Since M1.x a worktree charter cuts is wired as it is cut, so `false` now means a tree
	 *  cut by plain git, one whose wire did not land, or a plane with no layer to carry. The
	 *  row still says so, because a chat in such a tree runs without the plane's ask/deny
	 *  rules, without its persona's agents and without `$CHARTER_HARNESS` — and starting one
	 *  there is what writes the layer or refuses.
	 */
	wired: boolean,
	/**  Set when git still has a registration whose directory is gone. */
	stale: boolean,
};

/**
 *  One row of the profile picker: what it runs, where charter read it, and what pressing
 *  Enter on it would do.
 */
export type ProfileRow = {
	name: string,
	kind: string,
	/**
	 *  The environment and the command as one line a person reads, already contained: a
	 *  profile is a file a chat can write, and a control byte in it must never redraw a row.
	 */
	shown: string,
	/**  `built-in` or `charter.local.toml`. */
	source: string,
	/**  The row the picker starts on. It launches nothing by itself. */
	is_default: boolean,
	/**
	 *  `new` or `changed` when this profile's command must be shown and approved before it
	 *  runs; absent when charter has already recorded running exactly this.
	 */
	approval: string | null,
};

/**  One clone's git state, and what the forge cache last recorded for its branch. */
export type RepoState = {
	name: string,
	/**  The branch the checkout is on, where it is on one. */
	branch: string | null,
	/**  Whether that branch holds no commit yet. */
	unborn: boolean,
	/**  The commit HEAD sits on when it is on no branch. */
	detached: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	/**  Changed files git is tracking. */
	tracked: number,
	/**  Files git is not tracking. */
	untracked: number,
	/**
	 *  Why charter could not read the tree. Every count above is zero when this is set, and
	 *  it means charter does not know — not that the tree is clean.
	 */
	unreadable: string | null,
	/**  What the forge cache last recorded, one of the seven states charter knows. */
	ci: string | null,
	change: number | null,
	sigil: string | null,
	/**  How long ago the cache entry was written, which is how old this answer is. */
	fetched_seconds_ago: number | null,
	/**
	 *  Why there is nothing from the forge to show. Absent when something was fetched, even
	 *  when what was fetched named no pipeline.
	 */
	not_fetched: string | null,
};

/**  Every clone of one workspace, as the panels draw them. */
export type RepoStates = {
	workspace: string,
	repos: RepoState[],
	/**
	 *  Why the forge cache was not read at all, where it was not. Reported once for the
	 *  listing rather than repeated on every row.
	 */
	cache_refused: string | null,
};

/**
 *  The whole left-hand side: every workspace with its chats, and the focused workspace's
 *  persona and todos.
 */
export type Sidebar = {
	root: string,
	workspaces: SidebarWorkspace[],
	/**  The plane's personas, and the one a new chat here would adopt. */
	personas: string[],
	persona: string | null,
	/**  Chats whose directory is in no workspace, so the sidebar can still show them. */
	unfiled: OpenChat[],
};

/**
 *  One workspace as the sidebar draws it: what it is for, what it still means to do, and the
 *  chats working in it.
 */
export type SidebarWorkspace = {
	name: string,
	/**  Where the workspace is, so a chat can be started in it. */
	path: string,
	vision: string,
	todos: string[],
	chats: OpenChat[],
};

/**  Everything the picker draws, read from the plane when it is opened. */
export type StartOptions = {
	profiles: ProfileRow[],
	/**
	 *  Profiles charter read and will not use, by name and reason, so a row that is missing
	 *  is never merely missing.
	 */
	refused: ([string, string])[],
	personas: string[],
	/**  The plane's `[persona] default`, which is the persona row the picker starts on. */
	persona: string | null,
	/**
	 *  Set when git would carry `charter.local.toml`: every declared profile is refused
	 *  until it is fixed, and this is the one fix for that state.
	 */
	ignore_fix: string | null,
	/**
	 *  Whether this plane declares no profiles of its own. The built-ins still start, and
	 *  the picker says so rather than looking empty or broken.
	 */
	declares_none: boolean,
};

/**
 *  A chat that started: its session, and the one line to say if charter wired its profile
 *  on the way.
 */
export type Started = {
	session: number,
	wired: string | null,
};

/**
 *  A view a pane has open, and what its terminal has to match to show the session as it is:
 *  the size the screen was drawn for, so what was wrapped stays wrapped, and how much history
 *  the core is keeping, so the pane keeps the same.
 */
export type Watching = {
	view: number,
	columns: number,
	rows: number,
	scrollback: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

